spring:
  application:
    name: dataeureka
  profiles:
  - dev

---
server:
  port: 7001
spring:
  application:
    name: dataeureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: false