spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

feign:
  hystrix:
    enabled: true

spring:
  profiles: dev
  application:
    name: datauser
  datasource:
    username: temp
    password: temp
    url: jdbc:mysql://39.106.207.72:3306/datauser
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-wait-millis: 200
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: 305851718@qq.com
    password: cdfnmicrdqfdbhie
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    clusterNodes: 39.106.207.72:9361,39.106.207.72:9362,39.106.207.72:9363,39.106.207.72:9364,39.106.207.72:9365,39.106.207.72:9366
    commandTimeout: 12000  #redis操作的超时时间
    pool:
      maxActive: 500 #最大连接数
      maxIdle: 100 #最大空闲连接数
      minIdle: 5 #最小空闲连接数
      maxWait: 3000  #获取连接最大等待时间 ms  #default -1


mybatis:
  config-location: classpath:mybatis/mybatis.cfx.xml
  type-aliases-package: cn.com.datashare.datauser.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
