spring:
  profiles:
    active:
    - dev
---
server:
  port: 9527
spring:
  application:
    name: datazuul

feign:
  hystrix:
    enabled: true

zuul:
  ignored-services: "*"
  routes:
    mydept.serviceId: datauser
    mydept.path: /user/**
info:
  name: zuul