spring:
  profiles:
    active:
    - dev
---
server:
  port: 9527
spring:
  application:
    name: datazuul

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false   
zuul:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  ignored-services: "*"
  routes:
    mydept.serviceId: datauser
    mydept.path: /user/**

info:
  name: zuul