spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

feign:
  hystrix:
    enabled: true

spring:
  profiles: dev
  application:
    name: datauser
  datasource:
    username: temp
    password: temp
    url: jdbc:mysql://39.106.207.72:3306/datauser
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-wait-millis: 200
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: datashare
    password: wugkzqekgvgvbgid
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    timeout: 60000
    database: 0
    host: 39.106.207.72
    port: 8361
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 100
      min-idle: 20


mybatis:
  config-location: classpath:mybatis/mybatis.cfx.xml
  type-aliases-package: cn.com.datashare.datauser.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
