spring:
  profiles:
    active:
    - dev
---
server:
  port: 8002

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false   

spring:
  profiles: dev
  application:
    name: datamenu
  datasource:
    username: temp
    password: temp
    url: jdbc:mysql://39.106.207.72:3306/datamenu?useUnicode=true&amp;characterEncoding=utf8&amp;characterSetResults=utf8&amp;useSSL=false
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-wait-millis: 200
      initial-size: 5
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  config-location: classpath:mybatis/mybatis.cfx.xml
  type-aliases-package: cn.com.datashare.datamenu.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  open-in-view: false